### ISSUE TITLE
Community website push

### ISSUE THREAD

**Issue by ghost** [trabian/chef-forever#1]
Hi, thanks for this cookbook! Do you mind pushing it to the community website?

This would make the download faster. Also, you'll be able to pin the stable version up there and continue working on master. 

It's now dead simple to push it thanks to the new emeril gem (http://fnichol.github.io/emeril/).

**Comment by dwradcliffe** [comment]
Hi @vaskas, sorry it took so long but I've pushed the cookbook to the community site. http://community.opscode.com/cookbooks/forever

**Comment by ghost** [comment]
@dwradcliffe thanks!
